global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pgadmin'
    static_configs:
      - targets: ['pgadmin-exporter:9101']

  - job_name: 'mongodb'
    static_configs:
      - targets: [ 'mongodb-exporter:9216' ]

  - job_name: 'geoserver'
    static_configs:
      - targets: ['geoserver-exporter:9103']

  - job_name: 'mongoexpress'
    static_configs:
      - targets: ['mongoexpress-exporter:9104']

  - job_name: 'elasticsearch'
    metrics_path: /metrics
    static_configs:
      - targets: ['elasticsearch-exporter:9114']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
