# Generated by Django 4.0.10 on 2023-12-06 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='satellite_mission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.mission'),
            preserve_default=False,
        ),
    ]
