# Generated by Django 4.0.10 on 2024-04-30 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='converted_files',
        ),
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converted_files', to='core.data'),
        ),
    ]
