# Generated by Django 4.0.10 on 2023-11-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statellite_mission', models.CharField(max_length=255)),
                ('folder_locations', models.JSONField(blank=True, null=True)),
                ('ftp_server', models.CharField(max_length=255)),
                ('ftp_user_name', models.CharField(max_length=255)),
                ('ftp_password', models.CharField(max_length=255)),
                ('fpt_port', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
