# Generated by Django 4.0.10 on 2024-01-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mongo_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
