# Generated by Django 4.0.10 on 2023-12-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('data', 'file_name')},
        ),
    ]
