# Generated by Django 4.0.10 on 2023-12-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
