# Generated by Django 4.0.10 on 2023-11-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
