# Generated by Django 4.0.10 on 2023-12-11 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_data_satellite_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
