# Generated by Django 4.0.10 on 2023-11-29 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producedmessage_consumedmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumedmessage',
            old_name='consumed_message',
            new_name='message_id',
        ),
    ]
