# Generated by Django 4.0.10 on 2023-12-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_data_data_tag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('satellite_mission', 'date_tag')},
        ),
    ]
