# Generated by Django 4.0.10 on 2023-11-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuration_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='folder_locations',
            field=models.JSONField(blank=True, default={'HRV______', '_________', 'IR_087___', 'IR_108___', 'IR_016___', 'WV_073___', 'IR_120___', 'VIS006___', 'IR_134___', 'WV_062___', 'VIS008___', 'IR_039___', 'IR_097___'}, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='fpt_port',
            field=models.IntegerField(default=201),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='ftp_password',
            field=models.CharField(default='bar', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='ftp_server',
            field=models.CharField(default='localhost', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='ftp_user_name',
            field=models.CharField(default='foo', max_length=255),
        ),
    ]
