# Generated by Django 4.0.10 on 2023-11-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_configuration_folder_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='folder_locations',
            field=models.JSONField(blank=True, default={'chanel 01': '_________', 'chanel 02': 'HRV______', 'chanel 03': 'IR_016___', 'chanel 04': 'IR_039___', 'chanel 05': 'IR_087___', 'chanel 06': 'IR_097___', 'chanel 07': 'IR_108___', 'chanel 08': 'IR_120___', 'chanel 09': 'IR_134___', 'chanel 10': 'VIS006___', 'chanel 11': 'VIS008___', 'chanel 12': 'WV_062___', 'chanel 13': 'WV_073___'}, null=True),
        ),
    ]
