# Generated by Django 4.0.10 on 2023-12-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_data_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('cancelled', 'Cancelled'), ('ready', 'Ready'), ('error', 'Error'), ('downloading', 'Downloading'), ('done', 'Done')], max_length=255),
        ),
    ]
