# Generated by Django 4.0.10 on 2023-11-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_configuration_folder_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='statellite_mission',
            new_name='satellite_mission',
        ),
    ]
