# Generated by Django 4.0.10 on 2023-11-29 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_consumedmessage_consumed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumed',
            name='message_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
    ]
