# Generated by Django 4.0.10 on 2023-11-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_consumed_message_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Missions',
            new_name='Mission',
        ),
    ]
