# Generated by Django 4.0.10 on 2023-11-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_statellite_mission_configuration_satellite_mission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='fpt_port',
            new_name='ftp_port',
        ),
    ]
