# Generated by Django 4.0.10 on 2023-11-30 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_missions_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='satellite_mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='core.mission'),
        ),
    ]
